site_name: CCCM Cluster Analysis Playbook
theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - admonition
  - footnotes
pages:
    - Home: index.md
    - Products Menu: products.md
    - Templates: templates.md
    - Analytical Framework: framework.md
